services:
  postgres:
    image: postgres:16
    container_name: ai_news_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsdb
    ports:
      - "5434:5432"
